version: '2'
template:
  name: "Multiple Deployment Options"
  description: "Deploy a Fibonacci microservice to differnet compute options to compare them."
  required:
    - build
    - repo
    - deploy

toolchain:
  name: 'multiple-deployment-options-{{timestamp}}'

services:
  repo:
    service_id: githubpublic
    parameters:
      repo_name: 'multiple-deployment-options'
      repo_url: 'https://github.com/IBM-Bluemix/multiple-deployment-options'
      type: fork
      has_issues: false
  build:
    service_id: pipeline
    parameters:
      services:
        - repo
      name: '{{services.repo.parameters.repo_name}}'
      ui-pipeline: true
      configuration:
        content:
          $text: pipeline.yml
        env:
          REPO: repo
          CF_APP_NAME: '{{form.pipeline.parameters.deploy-app-name}}'
          SPACE_NAME: '{{form.pipeline.parameters.deploy-space}}'
          ORG_NAME: '{{form.pipeline.parameters.deploy-organization}}'
          REGION_ID: '{{form.pipeline.parameters.deploy-region}}'
        execute: true

#Deployment
form:
  pipeline:
    parameters:
      deploy-app-name: "fibonacci-service-{{timestamp}}"
    schema:
      $ref: deploy.json
